### ISSUE TITLE
Some teachers don't have any talks, even after data refresh

### ISSUE THREAD

**Issue by jakewilson** [dharmaseed/dharmaseed-android#47]
Ajahn Chah, for example, has no talks on the app, but according to the website, he has 11.

**Comment by jakewilson** [comment]
This is because the pre-seeded db that comes with the app (in `app/src/main/assets`) is incomplete.

@bb4242 I don't know how you seeded the app initially, but I assume you seeded it on the app initially, then copied it somehow? I don't know how to do this, so could you clear data on your app, then copy the new db and commit that?

**Comment by bb4242** [comment]
@jakewilson, yep, the way I had built the app previously was to run it (starting with nothing in the db), let it sync, and then copy the database off the phone/emulator using adb and add it as an asset in the android studio project.  The database itself lives in `/data/data/org.dharmaseed.android/databases/Dharmaseed.db`, but getting it off a non-rooted device is a little tricky (you can't just use `adb pull` because it won't have permissions for that directory).

Here's the full procedure in case you want to try it yourself:

1. Uninstall the app from your phone/emulator (necessary to wipe out any existing database)
2. Delete `app/assets/Dharmaseed.db` from the android studio project.  Throw caution to the winds and don't use the "safe delete" option because that will complain (rightly so) that that file is referenced in other parts of the project. :)
3. Install the app, run it, and let it sync
4. Find/install [adb](https://developer.android.com/studio/command-line/adb).  It's probably best to use the same version of adb that comes with the Android SDK; for me on linux, that lives in `~/Android/Sdk/platform-tools/adb`.
5. Run the following to extract the database:
```
$ ~/Android/Sdk/platform-tools/adb exec-out run-as org.dharmaseed.android cat /data/data/org.dharmaseed.android/databases/Dharmaseed.db > Dharmaseed.db
```
6. Add `Dharmaseed.db` back to the android studio project

It might be nice to automate this as part of the release build process at some point.

**Comment by jakewilson** [comment]
Thanks Brett! For all concerned, on OS X adb was located in `~/Library/Android/sdk/platform-tools`.
